### ISSUE TITLE
Accessing raw response data

### ISSUE THREAD

**Issue by zblesk** [piedoom/TumblrSharp#52]
Thanks for the great library! 

When I download posts from Tumblr, I extract what I need and store it in my database. However, I'd also like to store the response data as-is, in case I need something else from them later. 

I haven't found any way to access the raw response data, so I thought I could work around it by serializing it with Newtonsoft.Json.JsonConvert.SerializeObject(). 
This works well when the post type is Quote, but for a Text post, I get an exception:

```
The method or operation is not implemented.

   at DontPanic.TumblrSharp.Client.TrailThemeConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at assembly.method() in D:\path\to\filecs:line 62
```

Either of those (serialization or access to response data) would be great for me. Maybe I'm just missing something?

**Comment by Cataurus** [comment]
Some of the special converter classes for tumblr responses from our library do not implement writing in json's format, only reading. These are for example the notes or trials. The exception error, however, indicates an incorrect use.
For the implementation of the tumblr-api for C# this was not necessary.
If this should be necessary, the converters would have to implement this function.

**Comment by Cataurus** [comment]
With last release supported the converter classes the writing methods
